use_frameworks!

platform :ios, '10.0'

target 'HGLocationManager_Example' do
  pod 'HGLocationManager', :path => '../'

  target 'HGLocationManager_Tests' do
    inherit! :search_paths

    
  end
end
